### ISSUE TITLE
Adapt to the PCA9555 ? 

### ISSUE THREAD

**Issue by jpagliaccio** [hideakitai/PCA9547#1]
I was wondering if this code could be easily adapted to the PCA9555 IO Expander. Is it possible with simple include file changes?   

http://www.ti.com/product/PCA9555

Thanks

**Comment by hideakitai** [comment]
I'm sorry for late reply.
I think it is not suitable to adapt this library for PCA9555, because it has different architecture.
Thanks for your suggestion!
